---
- name: Playbook - Un-Install figlet
  hosts: planetexpress:!farnsworth
  connection: ssh
  gather_facts: yes


  tasks:
  - name: using apt to remove figlet
    ansible.builtin.apt:
      name: figlet
      state: absent
    become: yes

