---
- name: playbook - Install figlet # metadata
  hosts: planetexpress:!farnsworth # install only of planetexpress , and ignore farnsworth
  connection: ssh
  gather_facts: yes


  tasks:
    - name: using apt to install figlet 
      ansible.builtin.apt:
        name: figlet
        state: present 
      become: yes


