---
#learning about plabybook
- name: bootstrapping and new user creation
  hosts: raiders
  gather_facts: no

  vars:
    newuser1: marian
    newuser2: belloq
    newuser3: willie
    newuser4: elsa


  tasks:
    #use the raw module 

- name: update apt with latest repo info
  raw: "apt udpate -y"
  become: yes
- name: install py3 and pip3 with ansible raw
  raw: "apt install -y python3-pip"
  become: yes


  #create a new group
- name: create a new group
  group:
    name: indymovies
    state: present
  become:yes

- name: Add new user1 to target hosts
  user:
    name: "{{ newuser1 }}"
    state: present
    group: indymovies
  become: yes

  - name: add newuser2 to target hosts
    user:
      name: "{{ newuser2 }}"
      state: present
      group: indymovies
    become: yes


    - name: add newuser3 to target hosts
    user:
      name: "{{ newuser3 }}"
      state: present
      group: indymovies
    become: yes

    -name: add newuser4 to target hosts
     user: 
     name: "{{ newuser4 }}"
      state: presnet 
      group: indymovies
    become: yes
