---
- name: Exploring the template module and jinja expressions
  hosts: planetexpress
  gather_facts: no

  vars_files:
    - vars/planetexpress.yml


  tasks:
    - name: Configure Spaceship registartion
      template:
        src: templates/ship.cfg.j2
        dest: ~/ship.cfg

    - name: Configure mission orders
      template:
        src: templates/mission-orders.txt.j2
        dest: ~/mission-orders.txt
